### ISSUE TITLE
"Not enough arguments in call to transaction.MakePaymentTxn"

### ISSUE THREAD

**Issue by ghost** [jsign/algochat#1] opened 2019-04-11 20:18 UTC
After running `go get github.com/jsign/algochat` in the Terminal, though it seems to get the repo just fine, I'm greeted with the following error:

```
go/src/github.com/jsign/algochat/chatstream/chatstream.go:147:39: not enough arguments in call to transaction.MakePaymentTxn
	have (string, string, uint64, number, uint64, uint64, []byte, string)
	want (string, string, uint64, uint64, uint64, uint64, []byte, string, string)
```

The same error happens when trying to run algochat  (with necessary parameters filled in) with:
```
go run main.go -wallet funnywallet -walletpassword funnypassword123 -from <from-addr-from-your-wallet> -algodtoken <algod.token> -kmdtoken <kmd.token> -username bobgorand
```

Is there another recommended method to get the package to run or did I do something wrong? 😅

**Comment by jsign** [comment] 2019-04-11 20:37
Oh, yes... the problem is that `MakePaymentTxn` is using a older version of the current `master` of the SDK.
I'll soon fix it and include dependencies in the repo to avoid this problem in future too.

I'll get back to you here to retry!

**Comment by ghost** [comment] 2019-04-11 20:38
Awesome, I had a twinkling assumption that was probably it.

**Comment by jsign** [comment] 2019-04-12 01:10
Done, dependencies resolved with `dep`. 
Pull the `withvendor` branch and try again, if all went correctly I'll merge it to `master`.

Remember that you should use you own correct flags regarding `-wallet`, `-wallentpassword`, `-from`, `-algodtoken` and `-kmdtoken`. In `username` you can invent whatever nickname you want.

In case it might help others too, the following commands will help resolving those flags:
`goal wallet list`
`goal account list` (or `goal account -w <wallet.name> list` if not using the default wallet).

In case you're having troubles with the `algod.token` or `kmd.token`, stop both the node and kmd, delete the `.token` files, and start them again: `goal node start`  (remember `-d` flag if you're not using the env variable config), also recall that kmd doesn't start automatically with `goal node start`, so you should do `goal kmd start` too.

I also added this slight help commands to the Readme.

**Comment by jsign** [comment] 2019-04-12 02:41
I merged it into `master`.

I chatted with `andriko` which also was having this problem and already tested the fixed branch... we successfully chatted some minutes in Algochat. :)

I'll wait for your confirmation to close it.

**Comment by ghost** [comment] 2019-04-12 03:10
![Screen Shot 2019-04-11 at 10 07 29 PM](https://user-images.githubusercontent.com/49536083/56009764-970c4100-5ca6-11e9-976e-3eace1f584d0.png)

**Closed as completed** 2019-04-12 03:16 UTC
